## Data Collection
The crime dataset was collected from the open data portal of the "Organismo de Investigación Judicial" (OIJ) of Costa Rica [[1]](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)[[2]](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos). The dataset contains registered data from 2015 to 2025. The dataset to be downloaded was previously cleaned using OpenRefine.

Demographic and population datasets were sourced from the Costa Rican "Instituto Nacional de Estadística y Censos" (INEC) website [[3]](https://inec.cr/estadisticas-fuentes), while macroeconomic and socioeconomic indicators were retrieved from the World Bank database [[4]](https://data.worldbank.org/country/costa-rica).

### Downloading datasets
The datasets were uploaded to Google Drive because the crime dataset is too large to host directly. The datasets are available for download at [Datasets](https://drive.google.com/drive/u/0/folders/1LokpJjgchbPH62Q2NzNoRzVOeMNlTEsb).

In [1]:
import shutil
import os
import gdown

RAW_DATA_FOLDER = "../data/"

if os.path.exists(RAW_DATA_FOLDER):
    shutil.rmtree(RAW_DATA_FOLDER)

os.makedirs(RAW_DATA_FOLDER, exist_ok=True)

gdown.download_folder(
    id = "1LokpJjgchbPH62Q2NzNoRzVOeMNlTEsb",
    output = RAW_DATA_FOLDER,
    quiet = False)

Retrieving folder contents

Retrieving folder 1DZ5iS9ljVz36Z7ni1XrkDsyWyNJTp5b0 processed
Processing file 1fsnoAtS8zwC3vJLTFgPqFbemoqGbfxHp crime_data_2015_2025.csv
Processing file 1l0O21Ip41LCLjjF-20u5xzSChB61PHUc crime_data_2020.csv
Processing file 1icI67mwtEn0g8jf31JoeeBLzCg6Q_TPv crime_data_2021.csv
Processing file 1JT5XAlLqfdYSnWOld8Ek1-lL568Gr7oN crime_data_2022.csv
Processing file 1kjj_d4OmqZxYyfZTYZA7ATQ6P-9zdQg0 crime_data_2025.csv
Processing file 1Ay62tfv7VAegn1jRvoN3PTa616AHEkwu population_by_province_inec.csv
Processing file 1n46BUonyeWhlE_sncwrRvwSgMFjiiC66 population_indicators_inec.csv
Processing file 189N3Y6eXmtvwti1Nt7n0CRv1DxdQB-b8 socioeconomic_Indicators_world_bank.csv

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1fsnoAtS8zwC3vJLTFgPqFbemoqGbfxHp
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\crime_data_2015_2025.csv
100%|██████████| 97.3M/97.3M [00:04<00:00, 22.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1l0O21Ip41LCLjjF-20u5xzSChB61PHUc
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\crime_data_2020.csv
100%|██████████| 5.58M/5.58M [00:00<00:00, 11.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1icI67mwtEn0g8jf31JoeeBLzCg6Q_TPv
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\crime_data_2021.csv
100%|██████████| 5.93M/5.93M [00:00<00:00, 10.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JT5XAlLqfdYSnWOld8Ek1-lL568Gr7oN
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\crime_data_2022.csv
100%|██████████| 6.99M/6.99M [00:00<00:00, 11.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kjj_d4OmqZxYyfZTYZA7ATQ6P-9zdQg0
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\crime_data_2025.csv
100%|██████████| 5.66M/5.66M [00:00<00:00, 11.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ay62tfv7VAegn1jRvoN3PTa616AHEkwu
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\population_by_province_inec.csv
100%|██████████| 3.02k/3.02k [00:00<00:00, 4.50MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n46BUonyeWhlE_sncwrRvwSgMFjiiC66
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\population_indicators_inec.csv
100%|██████████| 2.71k/2.71k [00:00<00:00, 5.74MB/s]
Downloading...
From: https://drive.google.com/uc?id=189N3Y6eXmtvwti1Nt7n0CRv1DxdQB-b8
To: c:\Users\Randylaptop\Documents\Proyectos\costa-rica-crime-eda\data\socioeconomic_Indicators_world_bank.csv
100%|██████████| 5.46k/5.46k [00:00<00:00, 2.13MB/s]
Download completed

['../data/crime_data_2015_2025.csv',
 '../data/crime_data_2020.csv',
 '../data/crime_data_2021.csv',
 '../data/crime_data_2022.csv',
 '../data/crime_data_2025.csv',
 '../data/population_by_province_inec.csv',
 '../data/population_indicators_inec.csv',
 '../data/socioeconomic_Indicators_world_bank.csv']

### Reading The Crime Dataset

Not all columns will be used for this exploratory data analysis (EDA). Only a few columns will be selected due to inconsistencies in data utility across the years. For example, the exact hour of the registered crime was not recorded in certain years.

In [2]:
import pandas as pd

columns_to_keep = ["Delito", "SubDelito", "Fecha", "Provincia", "Canton"]
crime_data = pd.read_csv("../data/crime_data_2015_2025.csv", usecols=columns_to_keep)
display(crime_data.head(4))
display(crime_data.tail(4))

             Delito SubDelito                 Fecha   Provincia     Canton
0  Robo De Vehiculo  Descuido  2015-05-10T00:00:00Z    San Jose     Acosta
1  Robo De Vehiculo  Descuido  2015-07-01T00:00:00Z  Guanacaste  Abangares
2  Robo De Vehiculo  Descuido  2015-04-01T00:00:00Z    San Jose   San Jose
3  Robo De Vehiculo  Descuido  2015-04-01T00:00:00Z    San Jose   San Jose

,Delito,SubDelito,Fecha,Provincia,Canton
599600,Hurto,Carterista,2025-01-01T00:00:00Z,Guanacaste,Santa Cruz
599601,Robo,Forzadura,2025-01-01T00:00:00Z,Puntarenas,Osa
599602,Robo De Vehiculo,Cocherazo,2025-01-01T00:00:00Z,Guanacaste,Nicoya
599603,Robo De Vehiculo,Descuido,2025-01-01T00:00:00Z,San Jose,Tibas

In [3]:
crime_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 599604 entries, 0 to 599603
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Delito     599604 non-null  str
 1   SubDelito  599604 non-null  str
 2   Fecha      599604 non-null  str
 3   Provincia  599604 non-null  str
 4   Canton     599604 non-null  str
dtypes: str(5)
memory usage: 22.9 MB

#### Extracting year and month for each registered crime

In [4]:
crime_data["Fecha"] = pd.to_datetime(crime_data["Fecha"], errors="coerce")

crime_data["Año"] = crime_data["Fecha"].dt.year
crime_data["Mes"] = crime_data["Fecha"].dt.month

crime_data.drop(columns=["Fecha"], inplace=True, errors="ignore")

display(crime_data.head(3))
display(crime_data.tail(3))

             Delito SubDelito   Provincia     Canton   Año  Mes
0  Robo De Vehiculo  Descuido    San Jose     Acosta  2015    5
1  Robo De Vehiculo  Descuido  Guanacaste  Abangares  2015    7
2  Robo De Vehiculo  Descuido    San Jose   San Jose  2015    4

                  Delito  SubDelito   Provincia  Canton   Año  Mes
599601              Robo  Forzadura  Puntarenas     Osa  2025    1
599602  Robo De Vehiculo  Cocherazo  Guanacaste  Nicoya  2025    1
599603  Robo De Vehiculo   Descuido    San Jose   Tibas  2025    1

##### Missing data in the crime dataset
The original data for each year from 2015 to 2025 was retrieved from [[1]](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos) and concatenated into a single dataset. However, two years were missing certain months: 2020 was missing November and December, and December was missing from the 2021 data.

In [5]:
months_sorted = crime_data.groupby("Año")["Mes"].unique().apply(sorted)
print(months_sorted)

Año
2015    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2016    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2017    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2018    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2019    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2020            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2021        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
2022    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2023    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2024    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2025    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Name: Mes, dtype: object

##### Non-Standard Crime Categorization in 2022 and 2025

In the 2022 and 2025 datasets, the standard crime categorization differed from the other years.

##### Example of non-standard crime categorization:

In [6]:
data_2022 = crime_data[crime_data["Año"] == 2022]
data_2025 = crime_data[crime_data["Año"] == 2025]
print("Unique crime names in 2022:\n\n")
print(data_2022["Delito"].unique())

Unique crime names in 2022:


<StringArray>
[                 'Delitos Contra La Administracion De Justicia',
                           'Delitos Contra La Autoridad Publica',
                                    'Delitos Contra La Libertad',
                                   'Delitos Contra La Propiedad',
                                        'Delitos Contra La Vida',
                             'Delitos Contra La Seguridad Comun',
              'Delitos Contra Los Deberes De La Funcion Publica',
                                          'Delitos Informaticos',
                                'Estafas Y Otras Defraudaciones',
                                              'Delitos Sexuales',
                                                 'Otros Delitos',
                             'Otros Delitos Contra La Propiedad',
                                                     'No Delito',
                                     'Delitos Contra La Familia',
                          'Infraccion A La Ley De Psicotropicos',
                       'Infraccion A La Ley De Bienestar Animal',
                      'Delitos Contra El Ambito De La Intimidad',
                          'Ley Contra El Acoso Sexual Callejero',
                                       'Delitos Contra El Honor',
                                  'Delitos Contra La Fe Publica',
                                           'Delitos Ambientales',
                                             'Trata De Personas',
                     'Delitos Contra La Buena Fe Delos Negocios',
                        'Delitos Contra La Tranquilidad Publica',
                                                   'Desconocido',
                                           'Trafico De Personas',
 'Delitos Contra Los Poderes Publicos Y El Orden Constitucional']
Length: 27, dtype: str

In [7]:
print("Unique crime names in 2025:\n\n")
print(data_2025["Delito"].unique())

Unique crime names in 2025:


<StringArray>
[                                          'Asalto',
                                            'Hurto',
                                             'Robo',
                                 'Robo De Vehiculo',
                                        'Homicidio',
                                'Tacha De Vehiculo',
     'Delitos Contra La Administracion De Justicia',
                      'Delitos Contra La Propiedad',
                'Delitos Contra La Seguridad Comun',
                           'Delitos Contra La Vida',
                'Otros Delitos Contra La Propiedad',
 'Delitos Contra Los Deberes De La Funcion Publica',
                                 'Delitos Sexuales',
                   'Estafas Y Otras Defraudaciones',
                             'Delitos Informaticos',
             'Infraccion A La Ley De Psicotropicos',
                                        'No Delito',
                          'Delitos Contra El Honor',
                       'Delitos Contra La Libertad',
                                    'Otros Delitos',
         'Delitos Contra El Ambito De La Intimidad',
                        'Delitos Contra La Familia',
          'Infraccion A La Ley De Bienestar Animal',
             'Ley Contra El Acoso Sexual Callejero',
                              'Delitos Ambientales',
              'Delitos Contra La Autoridad Publica',
        'Delitos Contra La Buena Fe Delos Negocios',
                                'Trata De Personas',
                     'Delitos Contra La Fe Publica',
                                      'Desconocido',
           'Delitos Contra La Tranquilidad Publica']
Length: 31, dtype: str

The previously shown crimes categorization do not follow the standard classification structure used in other years:

In [8]:
data_2016 = crime_data[crime_data["Año"] == 2016]
print("Unique crime names in 2016:\n")
print(data_2016["Delito"].unique())
print()

data_2019 = crime_data[crime_data["Año"] == 2019]
print("Unique crime names in 2019:\n")
print(data_2019["Delito"].unique())
print()

data_2024 = crime_data[crime_data["Año"] == 2024]
print("Unique crime names in 2024:\n")
print(data_2024["Delito"].unique())

Unique crime names in 2016:

<StringArray>
['Robo De Vehiculo', 'Tacha De Vehiculo', 'Asalto', 'Homicidio', 'Hurto',
 'Robo']
Length: 6, dtype: str

Unique crime names in 2019:

<StringArray>
['Asalto', 'Homicidio', 'Hurto', 'Robo', 'Robo De Vehiculo',
 'Tacha De Vehiculo']
Length: 6, dtype: str

Unique crime names in 2024:

<StringArray>
['Asalto', 'Hurto', 'Robo De Vehiculo', 'Robo', 'Tacha De Vehiculo',
 'Homicidio']
Length: 6, dtype: str

#### Handling the new datasets for 2020-2022 and 2025

The process will proceed as follows:
1. Read the dataset for each year from the other source [[2]](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos).
2. Check consistency across these years to merge the data into a single Dataframe.
3. Perform data wrangling to the new data.
4. Merge the fixed data into the original dataset.

In [9]:
columns_to_keep = ["Delito", "SubDelito", "Fecha", "Provincia", "Canton"]

crimes_2020 = pd.read_csv("../data/crime_data_2020.csv", usecols=columns_to_keep)
crimes_2021 = pd.read_csv("../data/crime_data_2021.csv", usecols=columns_to_keep)
crimes_2022 = pd.read_csv("../data/crime_data_2022.csv", usecols=columns_to_keep)
crimes_2025 = pd.read_csv("../data/crime_data_2025.csv", usecols=columns_to_keep)

display(crimes_2020.head(2))
display(crimes_2020.tail(2))
display(crimes_2021.head(2))
display(crimes_2021.tail(2))
display(crimes_2022.head(2))
display(crimes_2022.tail(2))
display(crimes_2025.head(2))
display(crimes_2025.tail(2))

   Delito    SubDelito       Fecha Provincia     Canton
0  ASALTO  ARMA BLANCA  2020-01-03   HEREDIA    HEREDIA
1  ASALTO  ARMA BLANCA  2020-01-04   CARTAGO  EL GUARCO

,Delito,SubDelito,Fecha,Provincia,Canton
40413,TACHA DE VEHICULO,TACHA DE VEHICULO,2020-12-30,SAN JOSE,CURRIDABAT
40414,TACHA DE VEHICULO,TACHA DE VEHICULO,2020-06-01,SAN JOSE,DESAMPARADOS

   Delito    SubDelito       Fecha Provincia      Canton
0  ASALTO  ARMA BLANCA  2021-01-01  SAN JOSE  GOICOECHEA
1  ASALTO  ARMA BLANCA  2021-01-01  SAN JOSE    SAN JOSE

                  Delito          SubDelito       Fecha   Provincia    Canton
42696  TACHA DE VEHICULO  TACHA DE VEHICULO  2021-12-28  PUNTARENAS  GARABITO
42697  TACHA DE VEHICULO  TACHA DE VEHICULO  2021-12-22    ALAJUELA  ALAJUELA

   Delito    SubDelito       Fecha   Provincia   Canton
0  ASALTO  ARMA BLANCA  2022-01-03     HEREDIA  HEREDIA
1  ASALTO  ARMA BLANCA  2022-01-02  PUNTARENAS      OSA

,Delito,SubDelito,Fecha,Provincia,Canton
50554,TACHA DE VEHICULO,TACHA DE VEHICULO,2022-12-22,SAN JOSE,TIBAS
50555,TACHA DE VEHICULO,TACHA DE VEHICULO,2022-12-27,HEREDIA,SANTA BARBARA

   Delito    SubDelito       Fecha Provincia    Canton
0  ASALTO  ARMA BLANCA  2025-01-03  SAN JOSE  SAN JOSE
1  ASALTO  ARMA BLANCA  2025-01-08  ALAJUELA  ALAJUELA

                  Delito          SubDelito       Fecha Provincia    Canton
41012  TACHA DE VEHICULO  TACHA DE VEHICULO  2025-12-27  SAN JOSE  SAN JOSE
41013  TACHA DE VEHICULO  TACHA DE VEHICULO  2025-12-25  SAN JOSE  SAN JOSE

All of the new datasets follow the same structure, so they can be merged into a single DataFrame to simplify the workflow.

In [10]:
fixed_data = pd.concat([crimes_2020, crimes_2021, crimes_2022, crimes_2025], ignore_index=True)

In [11]:
fixed_data

,Delito,SubDelito,Fecha,Provincia,Canton
0,ASALTO,ARMA BLANCA,2020-01-03,HEREDIA,HEREDIA
1,ASALTO,ARMA BLANCA,2020-01-04,CARTAGO,EL GUARCO
2,ASALTO,ARMA BLANCA,2020-01-06,GUANACASTE,SANTA CRUZ
3,ASALTO,ARMA BLANCA,2020-01-04,CARTAGO,TURRIALBA
4,ASALTO,ARMA BLANCA,2020-01-07,SAN JOSE,SAN JOSE
...,...,...,...,...,...
174678,TACHA DE VEHICULO,TACHA DE VEHICULO,2025-12-30,SAN JOSE,SAN JOSE
174679,TACHA DE VEHICULO,TACHA DE VEHICULO,2025-12-27,SAN JOSE,PURISCAL
174680,TACHA DE VEHICULO,TACHA DE VEHICULO,2025-12-20,LIMON,LIMON
174681,TACHA DE VEHICULO,TACHA DE VEHICULO,2025-12-27,SAN JOSE,SAN JOSE
174682,TACHA DE VEHICULO,TACHA DE VEHICULO,2025-12-25,SAN JOSE,SAN JOSE

#### Extracting year and month for each registered crime

In [12]:
fixed_data["Fecha"] = pd.to_datetime(fixed_data["Fecha"], errors="coerce")
fixed_data["Año"] = fixed_data["Fecha"].dt.year
fixed_data["Mes"] = fixed_data["Fecha"].dt.month
fixed_data.drop(columns="Fecha", errors="ignore", inplace=True)
fixed_data

,Delito,SubDelito,Provincia,Canton,Año,Mes
0,ASALTO,ARMA BLANCA,HEREDIA,HEREDIA,2020,1
1,ASALTO,ARMA BLANCA,CARTAGO,EL GUARCO,2020,1
2,ASALTO,ARMA BLANCA,GUANACASTE,SANTA CRUZ,2020,1
3,ASALTO,ARMA BLANCA,CARTAGO,TURRIALBA,2020,1
4,ASALTO,ARMA BLANCA,SAN JOSE,SAN JOSE,2020,1
...,...,...,...,...,...,...
174678,TACHA DE VEHICULO,TACHA DE VEHICULO,SAN JOSE,SAN JOSE,2025,12
174679,TACHA DE VEHICULO,TACHA DE VEHICULO,SAN JOSE,PURISCAL,2025,12
174680,TACHA DE VEHICULO,TACHA DE VEHICULO,LIMON,LIMON,2025,12
174681,TACHA DE VEHICULO,TACHA DE VEHICULO,SAN JOSE,SAN JOSE,2025,12
174682,TACHA DE VEHICULO,TACHA DE VEHICULO,SAN JOSE,SAN JOSE,2025,12

#### Verifying complete months for 2020 and 2021

In [13]:
months_sorted = fixed_data.groupby("Año")["Mes"].unique().apply(sorted)
display(months_sorted)

Año
2020    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2021    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2022    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2025    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Name: Mes, dtype: object

All of the new datasets contain data for all months of each year.

#### Verifying the standard crime categorization structure

In [14]:
fixed_data["Delito"].unique()

<StringArray>
['ASALTO', 'HOMICIDIO', 'HURTO', 'ROBO', 'ROBO DE VEHICULO',
 'TACHA DE VEHICULO']
Length: 6, dtype: str

The new dataset share the same crime categorization structure as the other years.

#### Converting text columns to Title Case

In [15]:
columns_to_fix = ["Delito", "SubDelito", "Provincia", "Canton"]
fixed_data[columns_to_fix] = fixed_data[columns_to_fix].map(str.title)
fixed_data

,Delito,SubDelito,Provincia,Canton,Año,Mes
0,Asalto,Arma Blanca,Heredia,Heredia,2020,1
1,Asalto,Arma Blanca,Cartago,El Guarco,2020,1
2,Asalto,Arma Blanca,Guanacaste,Santa Cruz,2020,1
3,Asalto,Arma Blanca,Cartago,Turrialba,2020,1
4,Asalto,Arma Blanca,San Jose,San Jose,2020,1
...,...,...,...,...,...,...
174678,Tacha De Vehiculo,Tacha De Vehiculo,San Jose,San Jose,2025,12
174679,Tacha De Vehiculo,Tacha De Vehiculo,San Jose,Puriscal,2025,12
174680,Tacha De Vehiculo,Tacha De Vehiculo,Limon,Limon,2025,12
174681,Tacha De Vehiculo,Tacha De Vehiculo,San Jose,San Jose,2025,12
174682,Tacha De Vehiculo,Tacha De Vehiculo,San Jose,San Jose,2025,12

### Replacing the original data with the new data

Since the newly corrected dataset and the original dataset share the exact same structure, they can be merged into a single, consistent dataset.

In [16]:
display(crime_data.head(3))
display(fixed_data.head(3))

             Delito SubDelito   Provincia     Canton   Año  Mes
0  Robo De Vehiculo  Descuido    San Jose     Acosta  2015    5
1  Robo De Vehiculo  Descuido  Guanacaste  Abangares  2015    7
2  Robo De Vehiculo  Descuido    San Jose   San Jose  2015    4

   Delito    SubDelito   Provincia      Canton   Año  Mes
0  Asalto  Arma Blanca     Heredia     Heredia  2020    1
1  Asalto  Arma Blanca     Cartago   El Guarco  2020    1
2  Asalto  Arma Blanca  Guanacaste  Santa Cruz  2020    1

##### Deleting inconsistent crime data for 2020–2022 and 2025

The inconsistent crime data will be deleted from the original dataset to prepare for the merge.

In [17]:
crime_data = crime_data[(crime_data["Año"] != 2020) & (crime_data["Año"] != 2021)
                           & (crime_data["Año"] != 2022)
                           & (crime_data["Año"] != 2025)]

In [18]:
crime_data = pd.concat([crime_data, fixed_data], ignore_index=True)

In [19]:
display(crime_data.head(3))
display(crime_data.tail(3))

             Delito SubDelito   Provincia     Canton   Año  Mes
0  Robo De Vehiculo  Descuido    San Jose     Acosta  2015    5
1  Robo De Vehiculo  Descuido  Guanacaste  Abangares  2015    7
2  Robo De Vehiculo  Descuido    San Jose   San Jose  2015    4

                   Delito          SubDelito Provincia    Canton   Año  Mes
562622  Tacha De Vehiculo  Tacha De Vehiculo     Limon     Limon  2025   12
562623  Tacha De Vehiculo  Tacha De Vehiculo  San Jose  San Jose  2025   12
562624  Tacha De Vehiculo  Tacha De Vehiculo  San Jose  San Jose  2025   12

#### Validating the final fixes

##### Verifying completed months for each year

In [20]:
months_sorted = crime_data.groupby("Año")["Mes"].unique().apply(sorted)
display(months_sorted)

Año
2015    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2016    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2017    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2018    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2019    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2020    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2021    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2022    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2023    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2024    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2025    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Name: Mes, dtype: object

All years now contain the correct number of months.

##### Verifying the crime categorization structure

In [21]:
crime_data["Delito"].unique()

<StringArray>
['Robo De Vehiculo', 'Tacha De Vehiculo', 'Asalto', 'Homicidio', 'Hurto',
 'Robo']
Length: 6, dtype: str

The new dataset share the same crime categorization structure as the other years.

#### Translating the dataset into English

To make this project accessible to a global audience, the crime categories and column names will be translated from Spanish to English.

In [22]:
display(crime_data["Delito"].unique())
display(crime_data["SubDelito"].unique())
display(crime_data.columns)

<StringArray>
['Robo De Vehiculo', 'Tacha De Vehiculo', 'Asalto', 'Homicidio', 'Hurto',
 'Robo']
Length: 6, dtype: str

<StringArray>
[                      'Descuido',           'Otro O Indeterminado',
                  'Por Confianza',              'Tacha De Vehiculo',
                    'Arma Blanca',               'Arma Contundente',
                  'Arma De Fuego',                       'Arrebato',
                  'Candado Chino',                    'Desconocido',
                         'Golpes',                 'Inmovilizacion',
            'Intimidacion Verbal',                     'Uso De Gas',
     'Ajuste De Cuentas/venganza',                 'Discusion/riña',
                      'Femicidio',                 'No Determinado',
 'Por La Comision De Otro Delito',                    'Profesional',
  'Repeliendo Actividad Criminal',            'Violencia Domestica',
       'Ardid Previo/distraccion',                     'Carterista',
                      'Con Llave',                 'Ganzua/varilla',
                   'Por Descuido',                    'Progresivos',
    'Retiro De Cajero Automatico',               'Uso De Somnifero',
                        'Boquete',                 'Corta Candados',
                   'Escalamiento',                      'Forzadura',
                'Quitan Celosias',                'Ruptura Ventana',
                   'Ardid Previo',                         'Asalto',
                      'Cocherazo',     'Ajuste De Cuentas/Venganza',
            'Discusion/Ri&#209;A',       'Ardid Previo/Distraccion',
                 'Ganzua/Varilla',                     'Ideologico']
Length: 44, dtype: str

Index(['Delito', 'SubDelito', 'Provincia', 'Canton', 'Año', 'Mes'], dtype='str')

All Spanish terms will be translated into English. This process also highlights other errors in the data, such as:
- Incorrect encodings: "Discusion/RiÑ"
- Duplicate subcategories: "Ajuste De Cuentas/venganza" vs. "Ajuste De Cuentas/Venganza"

In [23]:
# Clean encoding issues and trailing spaces first to avoid mapping failures
crime_data['SubDelito'] = crime_data['SubDelito'].str.replace('&#209;', 'Ñ', regex=False)
crime_data['SubDelito'] = crime_data['SubDelito'].str.replace('&#241;', 'ñ', regex=False)
crime_data['SubDelito'] = crime_data['SubDelito'].str.strip()

# Complete dictionary for subcategories (SubDelito)
subcategory_translation = {
    'Descuido': 'Negligence / Left Unattended',
    'Otro O Indeterminado': 'Other or Undetermined',
    'Por Confianza': 'Breach of Trust',
    'Tacha De Vehiculo': 'Vehicle Breaking and Entering',
    'Arma Blanca': 'Edged Weapon / Knife',
    'Arma Contundente': 'Blunt Object',
    'Arma De Fuego': 'Firearm',
    'Arrebato': 'Snatching',
    'Candado Chino': 'Chokehold / Rear-Naked Choke',
    'Desconocido': 'Unknown',
    'Golpes': 'Physical Assault / Blows',
    'Inmovilizacion': 'Immobilization',
    'Intimidacion Verbal': 'Verbal Intimidation',
    'Uso De Gas': 'Use of Pepper Spray / Gas',
    'Ajuste De Cuentas/venganza': 'Score Settling / Revenge',
    'Ajuste De Cuentas/Venganza': 'Score Settling / Revenge',
    'Discusion/riña': 'Altercation / Fight',
    'Discusion/RiÑA': 'Altercation / Fight',
    'Femicidio': 'Femicide',
    'No Determinado': 'Undetermined',
    'Por La Comision De Otro Delito': 'During the Commission of Another Crime',
    'Profesional': 'Professional / Contract Killing',
    'Repeliendo Actividad Criminal': 'Repelling Criminal Activity',
    'Violencia Domestica': 'Domestic Violence',
    'Ardid Previo/distraccion': 'Distraction Scam',
    'Ardid Previo/Distraccion': 'Distraction Scam',
    'Carterista': 'Pickpocketing',
    'Con Llave': 'Using a Key / Lock Picking',
    'Ganzua/varilla': 'Using a Lockpick / Slim Jim',
    'Ganzua/Varilla': 'Using a Lockpick / Slim Jim',
    'Por Descuido': 'Left Unattended',
    'Progresivos': 'Progressive Theft',
    'Retiro De Cajero Automatico': 'ATM Withdrawal Theft',
    'Uso De Somnifero': 'Use of Soporifics / Drugging',
    'Boquete': 'Wall Tunneling / Wall Breach',
    'Corta Candados': 'Bolt Cutter Usage',
    'Escalamiento': 'Climbing / Scaling Walls',
    'Forzadura': 'Forced Entry',
    'Quitan Celosias': 'Louver Window Removal',
    'Ruptura Ventana': 'Window Shattering',
    'Ardid Previo': 'Deceptive Trick / Scam',
    'Asalto': 'Assault',
    'Cocherazo': 'Garage Break-in / Driveway Theft',
    'Ideologico': 'Ideological Motive'
}

# Apply subcategory translation
crime_data['SubDelito'] = crime_data['SubDelito'].map(subcategory_translation).fillna(crime_data['SubDelito'])

# Complete dictionary for main crime categories (Delito)
category_translation = {
    'Robo De Vehiculo': 'Vehicle Theft',
    'Tacha De Vehiculo': 'Vehicle Breaking and Entering',
    'Asalto': 'Assault',
    'Homicidio': 'Homicide',
    'Hurto': 'Theft',
    'Robo': 'Robbery'
}

# Apply category translation
crime_data['Delito'] = crime_data['Delito'].map(category_translation)

# Dictionary for column names
column_translation = {
    'Delito': 'Crime_category',
    'SubDelito': 'Crime_subcategory',
    'Provincia': 'Province',
    'Canton': 'Canton',
    'Año': 'Year',
    'Mes': 'Month'
}

# Rename the columns
crime_data = crime_data.rename(columns=column_translation)

In [24]:
crime_data

,Crime_category,Crime_subcategory,Province,Canton,Year,Month
0,Vehicle Theft,Negligence / Left Unattended,San Jose,Acosta,2015,5
1,Vehicle Theft,Negligence / Left Unattended,Guanacaste,Abangares,2015,7
2,Vehicle Theft,Negligence / Left Unattended,San Jose,San Jose,2015,4
3,Vehicle Theft,Negligence / Left Unattended,San Jose,San Jose,2015,4
4,Vehicle Theft,Negligence / Left Unattended,San Jose,Goicoechea,2015,7
...,...,...,...,...,...,...
562620,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San Jose,San Jose,2025,12
562621,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San Jose,Puriscal,2025,12
562622,Vehicle Breaking and Entering,Vehicle Breaking and Entering,Limon,Limon,2025,12
562623,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San Jose,San Jose,2025,12
562624,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San Jose,San Jose,2025,12

#### Adding missing accents to the provinces of San José and Limón

In [25]:
crime_data["Province"] = crime_data["Province"].replace(
    "San Jose",
    "San José"
)

crime_data["Province"] = crime_data["Province"].replace(
    "Limon",
    "Limón"
)

crime_data

,Crime_category,Crime_subcategory,Province,Canton,Year,Month
0,Vehicle Theft,Negligence / Left Unattended,San José,Acosta,2015,5
1,Vehicle Theft,Negligence / Left Unattended,Guanacaste,Abangares,2015,7
2,Vehicle Theft,Negligence / Left Unattended,San José,San Jose,2015,4
3,Vehicle Theft,Negligence / Left Unattended,San José,San Jose,2015,4
4,Vehicle Theft,Negligence / Left Unattended,San José,Goicoechea,2015,7
...,...,...,...,...,...,...
562620,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San José,San Jose,2025,12
562621,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San José,Puriscal,2025,12
562622,Vehicle Breaking and Entering,Vehicle Breaking and Entering,Limón,Limon,2025,12
562623,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San José,San Jose,2025,12
562624,Vehicle Breaking and Entering,Vehicle Breaking and Entering,San José,San Jose,2025,12

### Saving crime dataset

The cleaned crime dataset will be saved as a new CSV file to be used later in the exploratory data analysis (EDA)

In [26]:
crime_data.to_csv("../data/processed/crime_data.csv", index=False)

### Reading population and socioeconomic indicators
No significant changes are needed, as these dataset are already very clean.

#### Provincial Population Indicators
The next dataset provides the total population size for each province from 2015 to 2025.

In [27]:
population_by_province = pd.read_csv("../data/population_by_province_inec.csv")
population_by_province

    Provincia   Año  Población
0    Alajuela  2010     905675
1    Alajuela  2011     920600
2    Alajuela  2012     935069
3    Alajuela  2013     949251
4    Alajuela  2014     963514
..        ...   ...        ...
135  San José  2025    1662138
136  San José  2026    1666458
137  San José  2027    1670300
138  San José  2028    1673567
139  San José  2029    1676229

[140 rows x 3 columns]

##### Changing dataset indexing
To improve dataset manipulation during the EDA, using an index based on the year is much more effective.

In [28]:
population_by_province = population_by_province.pivot(index="Provincia",columns="Año", values="Población")
population_by_province

Año,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
Provincia,,,,,,,,,,,,,,,,,,,,
Alajuela,905675,920600,935069,949251,963514,977423,990846,1003571,1015703,1026100,1034594,1042259,1050190,1058895,1067200,1075129,1082783,1090195,1097272,1103985
Cartago,489995,495223,500140,504807,509379,513655,517586,521104,524263,526556,527870,528738,529690,531010,532077,532913,533566,534056,534356,534457
Guanacaste,342561,348521,354391,360203,366087,371871,377491,382859,388004,392476,396220,399614,403023,406746,410331,413767,417096,420333,423439,426428
Heredia,456885,464619,472145,479526,486909,494099,501042,507665,514009,519571,524245,528525,532871,537580,542110,546438,550613,554645,558496,562169
Limón,398535,404101,409383,414466,419552,424487,429248,433724,437961,441419,444088,446285,448645,451222,453600,455802,457883,459867,461717,463428
Puntarenas,432077,438143,444144,450172,456406,462598,468651,474413,479912,484542,488231,491511,494936,498693,502255,505637,508896,512054,515065,517919
San José,1506300,1523139,1539213,1554667,1569932,1584387,1597858,1610184,1621498,1630307,1636181,1640734,1645551,1651767,1657287,1662138,1666458,1670300,1673567,1676229

Only the data from 2015 to 2025 are relevant for this analysis. Therefore, the remaining columns can be dropped.

In [29]:
population_by_province = population_by_province.loc[:,2015:2025]
population_by_province

Año,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Provincia,,,,,,,,,,,
Alajuela,977423,990846,1003571,1015703,1026100,1034594,1042259,1050190,1058895,1067200,1075129
Cartago,513655,517586,521104,524263,526556,527870,528738,529690,531010,532077,532913
Guanacaste,371871,377491,382859,388004,392476,396220,399614,403023,406746,410331,413767
Heredia,494099,501042,507665,514009,519571,524245,528525,532871,537580,542110,546438
Limón,424487,429248,433724,437961,441419,444088,446285,448645,451222,453600,455802
Puntarenas,462598,468651,474413,479912,484542,488231,491511,494936,498693,502255,505637
San José,1584387,1597858,1610184,1621498,1630307,1636181,1640734,1645551,1651767,1657287,1662138

In [30]:
population_by_province.info()

<class 'pandas.DataFrame'>
Index: 7 entries, Alajuela to San José
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2015    7 non-null      int64
 1   2016    7 non-null      int64
 2   2017    7 non-null      int64
 3   2018    7 non-null      int64
 4   2019    7 non-null      int64
 5   2020    7 non-null      int64
 6   2021    7 non-null      int64
 7   2022    7 non-null      int64
 8   2023    7 non-null      int64
 9   2024    7 non-null      int64
 10  2025    7 non-null      int64
dtypes: int64(11)
memory usage: 672.0+ bytes

#### Population Growth and Density Indicators

The following dataset provides additional metrics, such as the annual increment, growth rate, and demographic density.

In [31]:
population_indicators = pd.read_csv("../data/population_indicators_inec.csv", index_col=["Provincia", "Año"])
population_indicators

               Crecimiento anual  Tasa de crecimiento (por cien habitantes)  \
Provincia Año
Alajuela  2015            13,909                                       1.43
          2016            13,423                                       1.36
          2017            12,725                                       1.28
          2018            12,132                                       1.20
          2019            10,397                                       1.02
...                          ...                                        ...
San José  2021             4,553                                       0.28
          2022             4,817                                       0.29
          2023             6,216                                       0.38
          2024             5,520                                       0.33
          2025             4,850                                       0.29

                Densidad demográfica ajustada (Total)
Provincia Año
Alajuela  2015                                  99.63
          2016                                 100.99
          2017                                 102.29
          2018                                 103.53
          2019                                 104.59
...                                               ...
San José  2021                                 330.14
          2022                                 331.11
          2023                                 332.36
          2024                                 333.47
          2025                                 334.45

[77 rows x 3 columns]

In [32]:
population_indicators.info()

<class 'pandas.DataFrame'>
MultiIndex: 77 entries, ('Alajuela', np.int64(2015)) to ('San José', np.int64(2025))
Data columns (total 3 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Crecimiento anual                          77 non-null     str
 1   Tasa de crecimiento (por cien habitantes)  77 non-null     float64
 2   Densidad demográfica ajustada (Total)      77 non-null     float64
dtypes: float64(2), str(1)
memory usage: 2.2+ KB

#### Translating the datasets into English

To be consistent with the language of the project, the column names of the population datasets will be translated from Spanish to English.

In [33]:
display(population_by_province.columns)
display(population_indicators.columns)

Index([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], dtype='int64', name='Año')

Index(['Crecimiento anual', 'Tasa de crecimiento (por cien habitantes)',
       'Densidad demográfica ajustada (Total)'],
      dtype='str')

In [34]:
# Translation dictionary for the main population dataset
population_by_province.columns.name = "Year"
population_by_province.index.name = "Province"

# Translation dictionary for the indicators dataset
indicators_translation = {
    "Crecimiento anual": "Annual_Growth",
    "Tasa de crecimiento (por cien habitantes)": "Growth_Rate_per_100",
    "Densidad demográfica ajustada (Total)": "Population_Density"
}

population_indicators = population_indicators.rename(columns=indicators_translation)
population_indicators = population_indicators.rename_axis(index={"Provincia": "Province", "Año": "Year"})

In [35]:
display(population_by_province)
display(population_indicators)

Year,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Province,,,,,,,,,,,
Alajuela,977423,990846,1003571,1015703,1026100,1034594,1042259,1050190,1058895,1067200,1075129
Cartago,513655,517586,521104,524263,526556,527870,528738,529690,531010,532077,532913
Guanacaste,371871,377491,382859,388004,392476,396220,399614,403023,406746,410331,413767
Heredia,494099,501042,507665,514009,519571,524245,528525,532871,537580,542110,546438
Limón,424487,429248,433724,437961,441419,444088,446285,448645,451222,453600,455802
Puntarenas,462598,468651,474413,479912,484542,488231,491511,494936,498693,502255,505637
San José,1584387,1597858,1610184,1621498,1630307,1636181,1640734,1645551,1651767,1657287,1662138

              Annual_Growth  Growth_Rate_per_100  Population_Density
Province Year
Alajuela 2015        13,909                 1.43               99.63
         2016        13,423                 1.36              100.99
         2017        12,725                 1.28              102.29
         2018        12,132                 1.20              103.53
         2019        10,397                 1.02              104.59
...                     ...                  ...                 ...
San José 2021         4,553                 0.28              330.14
         2022         4,817                 0.29              331.11
         2023         6,216                 0.38              332.36
         2024         5,520                 0.33              333.47
         2025         4,850                 0.29              334.45

[77 rows x 3 columns]

#### Socioeconomic data

The next dataset provides macroeconomic data for Costa Rica. It includes indicators such as the unemployment rate, labor force participation, and others.

In [36]:
socioeconomic_data = pd.read_csv("../data/socioeconomic_Indicators_world_bank.csv")
socioeconomic_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Costa Rica,CRI,"Labor force participation rate, total (% of to...",SL.TLF.CACT.NE.ZS,NaN,NaN,NaN,53.812000,NaN,NaN,...,59.848000,62.210000,64.263000,60.629000,61.766000,61.491000,56.831000,57.687000,55.935,NaN
1,Costa Rica,CRI,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.NE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.729000,9.010000,10.807000,16.432000,15.139000,11.325000,8.325000,6.936000,6.342,NaN
2,Costa Rica,CRI,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.790206,2.430794,2.67786,2.931618,3.324033,-0.665,...,1.625907,2.221115,2.096046,0.724911,1.726478,8.274775,0.525194,-0.412853,NaN,NaN
3,Costa Rica,CRI,Gini index,SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,...,48.300000,48.000000,48.200000,49.200000,48.700000,47.200000,46.700000,45.800000,45.500,NaN
4,Costa Rica,CRI,Poverty gap at $3.00 a day (2021 PPP) (%),SI.POV.GAPS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.600000,0.900000,0.600000,1.300000,0.700000,0.500000,0.500000,0.400000,0.200,NaN
5,Costa Rica,CRI,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,22.100000,22.900000,23.900000,30.000000,26.200000,25.500000,24.400000,20.300000,17.100,NaN
6,Costa Rica,CRI,"Lower secondary completion rate, total (% of r...",SE.SEC.CMPT.LO.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,56.412071,66.075569,70.422607,65.387268,67.588173,65.270561,62.284210,61.386978,NaN,NaN
7,Costa Rica,CRI,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,30.151421,26.086670,32.591579,30.082211,31.166620,21.581961,20.378830,NaN,NaN,NaN

The crime dataset only contains data from 2015 to 2025; therefore, only socioeconomic data from 2015 to 2025 will be used in the EDA.

In [37]:
socioeconomic_data.drop("Country Code", axis=1, errors="ignore", inplace=True)
socioeconomic_data.drop("Country Name", axis=1, errors="ignore", inplace=True)
socioeconomic_data.drop("Unnamed: 70", axis=1, errors="ignore", inplace=True)
drop_columns = list(socioeconomic_data.loc[:,"1960":"2014"])
socioeconomic_data.drop(drop_columns,  axis=1, errors="ignore", inplace=True)
socioeconomic_data

,Indicator Name,Indicator Code,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,"Labor force participation rate, total (% of to...",SL.TLF.CACT.NE.ZS,62.808000,59.687000,59.848000,62.210000,64.263000,60.629000,61.766000,61.491000,56.831000,57.687000,55.935
1,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.NE.ZS,8.415000,8.085000,7.729000,9.010000,10.807000,16.432000,15.139000,11.325000,8.325000,6.936000,6.342
2,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,0.801982,-0.017479,1.625907,2.221115,2.096046,0.724911,1.726478,8.274775,0.525194,-0.412853,NaN
3,Gini index,SI.POV.GINI,48.400000,48.700000,48.300000,48.000000,48.200000,49.200000,48.700000,47.200000,46.700000,45.800000,45.500
4,Poverty gap at $3.00 a day (2021 PPP) (%),SI.POV.GAPS,0.900000,0.800000,0.600000,0.900000,0.600000,1.300000,0.700000,0.500000,0.500000,0.400000,0.200
5,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,23.600000,22.900000,22.100000,22.900000,23.900000,30.000000,26.200000,25.500000,24.400000,20.300000,17.100
6,"Lower secondary completion rate, total (% of r...",SE.SEC.CMPT.LO.ZS,54.110489,54.544380,56.412071,66.075569,70.422607,65.387268,67.588173,65.270561,62.284210,61.386978,NaN
7,"Government expenditure on education, total (% ...",SE.XPD.TOTL.GB.ZS,23.373430,23.423201,30.151421,26.086670,32.591579,30.082211,31.166620,21.581961,20.378830,NaN,NaN

In [38]:
socioeconomic_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Indicator Name  8 non-null      str
 1   Indicator Code  8 non-null      str
 2   2015            8 non-null      float64
 3   2016            8 non-null      float64
 4   2017            8 non-null      float64
 5   2018            8 non-null      float64
 6   2019            8 non-null      float64
 7   2020            8 non-null      float64
 8   2021            8 non-null      float64
 9   2022            8 non-null      float64
 10  2023            8 non-null      float64
 11  2024            7 non-null      float64
 12  2025            5 non-null      float64
dtypes: float64(11), str(2)
memory usage: 964.0 bytes

### Saving population and socioeconomic datataset

The three datasets will be saved individually as CSV files for future use in the Exploratory Data Analysis phase.

In [39]:
population_by_province.to_csv("../data/processed/population_by_province.csv")
population_indicators.to_csv("../data/processed/population_indicators.csv")
socioeconomic_data.to_csv("../data/processed/socioeconomic_data.csv", index=False)